spring:
  datasource:
    username: root
    password: mysecretpassword
    url: jdbc:mysql://192.168.64.3:3306/gulimall_xms
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml    # 配置 mapper 文件的位置
  global-config:
    db-config:
      id-type: auto  # 配置主键生成规则