spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu

## 前端项目， /api
## http://localhost:88/api/captcha.jpg  http://localhost:8080/renren-fast/captcha.jpg

